os: linux
language: node_js
node_js:
  - "10"
  - "12"
cache:
  directories:
    - node_modules
env:
  global:
    - BUILD_REACT=true
script:
  - npm run lint
  - npm run test
  - npm run test:orc-shared
after_success: npm run coveralls
