language: node_js
node_js:
  - "10"
  - "12"
cache:
  directories:
    - "node_modules"
env:
  - BUILD_REACT=true
script:
  - "npm run coverage"
  - "npm run build:orc-shared"
after_success: "npm run coveralls"
