os: linux
language: node_js
node_js:
  - "10"
  - "12"
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm run coverage
  - npm run test:orc-shared
after_success: npm run coveralls
before_deploy: export NPM_TAG=`node src getDist`
deploy:
  provider: npm
  edge: true
  email: joclefrancois@gmail.com
  api_token:
    secure: jNpL4M9KHYxlhXFWMsZuyMqknOFYk+QPYsaTzk8WCWjcLDMSipGEbA1NaULjyx8DtatlY6iMbxGSZvMNp++5mAVSywnTDkioM/AAUIXhiUuu7qUnrmmph0cpLzlq4AwqkE8b1ni0WBP9X7HOmTIqY5Csd+qt2TlMe7uXpdXsxckzmSEh2KHJam/YcYQySJ5xQqnVS3XXqN7cTnPVlZj/GIO7SlNcMrJw23VtaBg1ANqfSA7kH6cXdtT2EJzrkTbzd/I3eX1IYOBQwEGigCi8ZanNS+OedK1D52XL7+q59cL0IbYHRxLCVdu6oVlzzabfG3hLFjZzc59ieLQQLYjCj6T6teBjX96TlQgBB+myne6wkZuOo/hlOOW9528kajwahWKJ8pqslyhBk0sIQ3tnrRC71L4Dgo3aoWC5TgIodaYdkTg/07Ex6Rly1CQXOEmfIDJ+lChGG1PFHZ6/UEm9ZBUryI0KrbczR0fOJBuIfnNNQR2x712DtwtKkGXSQJBwyRkGXObhxTB/WMCBjsStP6wZzgSvuDqV6WgZJmUEJHzqCfk4PIjiWKZYYzGi7aHe+zXI7E86s05B5dPlYWPOiKcdLUv+T4Z5SzpfMkViwX4w/uPRiZhn8cM5Fb9lvxzZEoKH85RU+aXA4v0UDKlQDqdenw9EsTRNdqwqPO4qTaY=
  tag: "$NPM_TAG"
  on:
    repo: Orckestra/orc-scripts
    tags: true
    condition: "$TRAVIS_NODE_VERSION = 12"
