// flow-typed signature: 457cbab9fe549ab6e330f489c706e2b6
// flow-typed version: <<STUB>>/is-ci_v1.1.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-ci'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "is-ci" {
	declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "is-ci/bin" {
	declare module.exports: any;
}

declare module "is-ci/test" {
	declare module.exports: any;
}

// Filename aliases
declare module "is-ci/bin.js" {
	declare module.exports: $Exports<"is-ci/bin">;
}
declare module "is-ci/index" {
	declare module.exports: $Exports<"is-ci">;
}
declare module "is-ci/index.js" {
	declare module.exports: $Exports<"is-ci">;
}
declare module "is-ci/test.js" {
	declare module.exports: $Exports<"is-ci/test">;
}
