// flow-typed signature: 6df666d4ca0526511419c7eb31ef1d6a
// flow-typed version: <<STUB>>/pkg-dir_v^2.0.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pkg-dir'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pkg-dir' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'pkg-dir/index' {
  declare module.exports: $Exports<'pkg-dir'>;
}
declare module 'pkg-dir/index.js' {
  declare module.exports: $Exports<'pkg-dir'>;
}
