// flow-typed signature: 68426192e2c00a758b5cc388b753566f
// flow-typed version: <<STUB>>/unexpected-react_v5.0.1/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'unexpected-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'unexpected-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'unexpected-react/jest' {
  declare module.exports: any;
}

declare module 'unexpected-react/lib/assertions/AssertionGenerator' {
  declare module.exports: any;
}

declare module 'unexpected-react/lib/assertions/deepAgainstRawAssertions' {
  declare module.exports: any;
}

declare module 'unexpected-react/lib/assertions/deepAssertions' {
  declare module.exports: any;
}

declare module 'unexpected-react/lib/assertions/jestSnapshotStandardRendererAssertions' {
  declare module.exports: any;
}

declare module 'unexpected-react/lib/assertions/jestSnapshotTestRendererAssertions' {
  declare module.exports: any;
}

declare module 'unexpected-react/lib/assertions/shallowAgainstRawAssertions' {
  declare module.exports: any;
}

declare module 'unexpected-react/lib/assertions/shallowAssertions' {
  declare module.exports: any;
}

declare module 'unexpected-react/lib/assertions/snapshotFunctionAssertions' {
  declare module.exports: any;
}

declare module 'unexpected-react/lib/assertions/snapshotFunctionType' {
  declare module.exports: any;
}

declare module 'unexpected-react/lib/assertions/testRendererAgainstRawAssertions' {
  declare module.exports: any;
}

declare module 'unexpected-react/lib/assertions/testRendererAssertions' {
  declare module.exports: any;
}

declare module 'unexpected-react/lib/helpers/snapshotLoader' {
  declare module.exports: any;
}

declare module 'unexpected-react/lib/helpers/snapshots' {
  declare module.exports: any;
}

declare module 'unexpected-react/lib/jest' {
  declare module.exports: any;
}

declare module 'unexpected-react/lib/react-native' {
  declare module.exports: any;
}

declare module 'unexpected-react/lib/reactEventNames' {
  declare module.exports: any;
}

declare module 'unexpected-react/lib/test-renderer-jest' {
  declare module.exports: any;
}

declare module 'unexpected-react/lib/test-renderer' {
  declare module.exports: any;
}

declare module 'unexpected-react/lib/types/dom-types' {
  declare module.exports: any;
}

declare module 'unexpected-react/lib/types/test-renderer-type-wrapper' {
  declare module.exports: any;
}

declare module 'unexpected-react/lib/types/types' {
  declare module.exports: any;
}

declare module 'unexpected-react/lib/unexpected-react' {
  declare module.exports: any;
}

declare module 'unexpected-react/react-native' {
  declare module.exports: any;
}

declare module 'unexpected-react/src/assertions/AssertionGenerator' {
  declare module.exports: any;
}

declare module 'unexpected-react/src/assertions/deepAgainstRawAssertions' {
  declare module.exports: any;
}

declare module 'unexpected-react/src/assertions/deepAssertions' {
  declare module.exports: any;
}

declare module 'unexpected-react/src/assertions/jestSnapshotStandardRendererAssertions' {
  declare module.exports: any;
}

declare module 'unexpected-react/src/assertions/jestSnapshotTestRendererAssertions' {
  declare module.exports: any;
}

declare module 'unexpected-react/src/assertions/shallowAgainstRawAssertions' {
  declare module.exports: any;
}

declare module 'unexpected-react/src/assertions/shallowAssertions' {
  declare module.exports: any;
}

declare module 'unexpected-react/src/assertions/snapshotFunctionAssertions' {
  declare module.exports: any;
}

declare module 'unexpected-react/src/assertions/snapshotFunctionType' {
  declare module.exports: any;
}

declare module 'unexpected-react/src/assertions/testRendererAgainstRawAssertions' {
  declare module.exports: any;
}

declare module 'unexpected-react/src/assertions/testRendererAssertions' {
  declare module.exports: any;
}

declare module 'unexpected-react/src/helpers/snapshotLoader' {
  declare module.exports: any;
}

declare module 'unexpected-react/src/helpers/snapshots' {
  declare module.exports: any;
}

declare module 'unexpected-react/src/jest' {
  declare module.exports: any;
}

declare module 'unexpected-react/src/react-native' {
  declare module.exports: any;
}

declare module 'unexpected-react/src/reactEventNames' {
  declare module.exports: any;
}

declare module 'unexpected-react/src/test-renderer-jest' {
  declare module.exports: any;
}

declare module 'unexpected-react/src/test-renderer' {
  declare module.exports: any;
}

declare module 'unexpected-react/src/types/dom-types' {
  declare module.exports: any;
}

declare module 'unexpected-react/src/types/test-renderer-type-wrapper' {
  declare module.exports: any;
}

declare module 'unexpected-react/src/types/types' {
  declare module.exports: any;
}

declare module 'unexpected-react/src/unexpected-react' {
  declare module.exports: any;
}

declare module 'unexpected-react/test-renderer-jest' {
  declare module.exports: any;
}

declare module 'unexpected-react/test-renderer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'unexpected-react/jest.js' {
  declare module.exports: $Exports<'unexpected-react/jest'>;
}
declare module 'unexpected-react/lib/assertions/AssertionGenerator.js' {
  declare module.exports: $Exports<'unexpected-react/lib/assertions/AssertionGenerator'>;
}
declare module 'unexpected-react/lib/assertions/deepAgainstRawAssertions.js' {
  declare module.exports: $Exports<'unexpected-react/lib/assertions/deepAgainstRawAssertions'>;
}
declare module 'unexpected-react/lib/assertions/deepAssertions.js' {
  declare module.exports: $Exports<'unexpected-react/lib/assertions/deepAssertions'>;
}
declare module 'unexpected-react/lib/assertions/jestSnapshotStandardRendererAssertions.js' {
  declare module.exports: $Exports<'unexpected-react/lib/assertions/jestSnapshotStandardRendererAssertions'>;
}
declare module 'unexpected-react/lib/assertions/jestSnapshotTestRendererAssertions.js' {
  declare module.exports: $Exports<'unexpected-react/lib/assertions/jestSnapshotTestRendererAssertions'>;
}
declare module 'unexpected-react/lib/assertions/shallowAgainstRawAssertions.js' {
  declare module.exports: $Exports<'unexpected-react/lib/assertions/shallowAgainstRawAssertions'>;
}
declare module 'unexpected-react/lib/assertions/shallowAssertions.js' {
  declare module.exports: $Exports<'unexpected-react/lib/assertions/shallowAssertions'>;
}
declare module 'unexpected-react/lib/assertions/snapshotFunctionAssertions.js' {
  declare module.exports: $Exports<'unexpected-react/lib/assertions/snapshotFunctionAssertions'>;
}
declare module 'unexpected-react/lib/assertions/snapshotFunctionType.js' {
  declare module.exports: $Exports<'unexpected-react/lib/assertions/snapshotFunctionType'>;
}
declare module 'unexpected-react/lib/assertions/testRendererAgainstRawAssertions.js' {
  declare module.exports: $Exports<'unexpected-react/lib/assertions/testRendererAgainstRawAssertions'>;
}
declare module 'unexpected-react/lib/assertions/testRendererAssertions.js' {
  declare module.exports: $Exports<'unexpected-react/lib/assertions/testRendererAssertions'>;
}
declare module 'unexpected-react/lib/helpers/snapshotLoader.js' {
  declare module.exports: $Exports<'unexpected-react/lib/helpers/snapshotLoader'>;
}
declare module 'unexpected-react/lib/helpers/snapshots.js' {
  declare module.exports: $Exports<'unexpected-react/lib/helpers/snapshots'>;
}
declare module 'unexpected-react/lib/jest.js' {
  declare module.exports: $Exports<'unexpected-react/lib/jest'>;
}
declare module 'unexpected-react/lib/react-native.js' {
  declare module.exports: $Exports<'unexpected-react/lib/react-native'>;
}
declare module 'unexpected-react/lib/reactEventNames.js' {
  declare module.exports: $Exports<'unexpected-react/lib/reactEventNames'>;
}
declare module 'unexpected-react/lib/test-renderer-jest.js' {
  declare module.exports: $Exports<'unexpected-react/lib/test-renderer-jest'>;
}
declare module 'unexpected-react/lib/test-renderer.js' {
  declare module.exports: $Exports<'unexpected-react/lib/test-renderer'>;
}
declare module 'unexpected-react/lib/types/dom-types.js' {
  declare module.exports: $Exports<'unexpected-react/lib/types/dom-types'>;
}
declare module 'unexpected-react/lib/types/test-renderer-type-wrapper.js' {
  declare module.exports: $Exports<'unexpected-react/lib/types/test-renderer-type-wrapper'>;
}
declare module 'unexpected-react/lib/types/types.js' {
  declare module.exports: $Exports<'unexpected-react/lib/types/types'>;
}
declare module 'unexpected-react/lib/unexpected-react.js' {
  declare module.exports: $Exports<'unexpected-react/lib/unexpected-react'>;
}
declare module 'unexpected-react/react-native.js' {
  declare module.exports: $Exports<'unexpected-react/react-native'>;
}
declare module 'unexpected-react/src/assertions/AssertionGenerator.js' {
  declare module.exports: $Exports<'unexpected-react/src/assertions/AssertionGenerator'>;
}
declare module 'unexpected-react/src/assertions/deepAgainstRawAssertions.js' {
  declare module.exports: $Exports<'unexpected-react/src/assertions/deepAgainstRawAssertions'>;
}
declare module 'unexpected-react/src/assertions/deepAssertions.js' {
  declare module.exports: $Exports<'unexpected-react/src/assertions/deepAssertions'>;
}
declare module 'unexpected-react/src/assertions/jestSnapshotStandardRendererAssertions.js' {
  declare module.exports: $Exports<'unexpected-react/src/assertions/jestSnapshotStandardRendererAssertions'>;
}
declare module 'unexpected-react/src/assertions/jestSnapshotTestRendererAssertions.js' {
  declare module.exports: $Exports<'unexpected-react/src/assertions/jestSnapshotTestRendererAssertions'>;
}
declare module 'unexpected-react/src/assertions/shallowAgainstRawAssertions.js' {
  declare module.exports: $Exports<'unexpected-react/src/assertions/shallowAgainstRawAssertions'>;
}
declare module 'unexpected-react/src/assertions/shallowAssertions.js' {
  declare module.exports: $Exports<'unexpected-react/src/assertions/shallowAssertions'>;
}
declare module 'unexpected-react/src/assertions/snapshotFunctionAssertions.js' {
  declare module.exports: $Exports<'unexpected-react/src/assertions/snapshotFunctionAssertions'>;
}
declare module 'unexpected-react/src/assertions/snapshotFunctionType.js' {
  declare module.exports: $Exports<'unexpected-react/src/assertions/snapshotFunctionType'>;
}
declare module 'unexpected-react/src/assertions/testRendererAgainstRawAssertions.js' {
  declare module.exports: $Exports<'unexpected-react/src/assertions/testRendererAgainstRawAssertions'>;
}
declare module 'unexpected-react/src/assertions/testRendererAssertions.js' {
  declare module.exports: $Exports<'unexpected-react/src/assertions/testRendererAssertions'>;
}
declare module 'unexpected-react/src/helpers/snapshotLoader.js' {
  declare module.exports: $Exports<'unexpected-react/src/helpers/snapshotLoader'>;
}
declare module 'unexpected-react/src/helpers/snapshots.js' {
  declare module.exports: $Exports<'unexpected-react/src/helpers/snapshots'>;
}
declare module 'unexpected-react/src/jest.js' {
  declare module.exports: $Exports<'unexpected-react/src/jest'>;
}
declare module 'unexpected-react/src/react-native.js' {
  declare module.exports: $Exports<'unexpected-react/src/react-native'>;
}
declare module 'unexpected-react/src/reactEventNames.js' {
  declare module.exports: $Exports<'unexpected-react/src/reactEventNames'>;
}
declare module 'unexpected-react/src/test-renderer-jest.js' {
  declare module.exports: $Exports<'unexpected-react/src/test-renderer-jest'>;
}
declare module 'unexpected-react/src/test-renderer.js' {
  declare module.exports: $Exports<'unexpected-react/src/test-renderer'>;
}
declare module 'unexpected-react/src/types/dom-types.js' {
  declare module.exports: $Exports<'unexpected-react/src/types/dom-types'>;
}
declare module 'unexpected-react/src/types/test-renderer-type-wrapper.js' {
  declare module.exports: $Exports<'unexpected-react/src/types/test-renderer-type-wrapper'>;
}
declare module 'unexpected-react/src/types/types.js' {
  declare module.exports: $Exports<'unexpected-react/src/types/types'>;
}
declare module 'unexpected-react/src/unexpected-react.js' {
  declare module.exports: $Exports<'unexpected-react/src/unexpected-react'>;
}
declare module 'unexpected-react/test-renderer-jest.js' {
  declare module.exports: $Exports<'unexpected-react/test-renderer-jest'>;
}
declare module 'unexpected-react/test-renderer.js' {
  declare module.exports: $Exports<'unexpected-react/test-renderer'>;
}
