// flow-typed signature: d97e50a10c94ffc9ae680a8f4d63e7d7
// flow-typed version: <<STUB>>/unexpected-sinon_v10.8.2/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'unexpected-sinon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "unexpected-sinon" {
	declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "unexpected-sinon/bootstrap-unexpected-markdown" {
	declare module.exports: any;
}

declare module "unexpected-sinon/lib/unexpected-sinon" {
	declare module.exports: any;
}

declare module "unexpected-sinon/test/monkeyPatchSinonStackFrames" {
	declare module.exports: any;
}

declare module "unexpected-sinon/test/unexpected-sinon.spec" {
	declare module.exports: any;
}

declare module "unexpected-sinon/vendor/mocha" {
	declare module.exports: any;
}

// Filename aliases
declare module "unexpected-sinon/bootstrap-unexpected-markdown.js" {
	declare module.exports: $Exports<
		"unexpected-sinon/bootstrap-unexpected-markdown",
	>;
}
declare module "unexpected-sinon/lib/unexpected-sinon.js" {
	declare module.exports: $Exports<"unexpected-sinon/lib/unexpected-sinon">;
}
declare module "unexpected-sinon/test/monkeyPatchSinonStackFrames.js" {
	declare module.exports: $Exports<
		"unexpected-sinon/test/monkeyPatchSinonStackFrames",
	>;
}
declare module "unexpected-sinon/test/unexpected-sinon.spec.js" {
	declare module.exports: $Exports<
		"unexpected-sinon/test/unexpected-sinon.spec",
	>;
}
declare module "unexpected-sinon/vendor/mocha.js" {
	declare module.exports: $Exports<"unexpected-sinon/vendor/mocha">;
}
